# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: ""
author: ""
description: "Mohamed Fathi Abdallah ©2023"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
icon: # the emoji used as the favicon
mathjax: true
url: "http://www.mfathiabdallah.com" # the base hostname & protocol for your site

# Layout
show_social: true 
show_excerpts: false      # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header
minimal: true            # use a dark header

# Menu

navigation:          # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV & Publications", file: "publications.md"}
  - {title: "More About Me", file: "more_about_me.md"}
  - {title: "News & Views", file: "blogs.md"}
  - {title: "Contact", file: "contact.md"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:"}
  - {title: Twitter, icon: twitter, url: ""}
  - {title: Linkedin, icon: linkedin, url: ""}
  - {title: Researchgate, icon: researchgate, url: ""}
  - {title: GoogleScholar, icon: user-graduate, url: ""}
  - {title: Orcid, icon: orcid, url: ""}
  - {title: Ghent University, icon: landmark, url: ""}

 #- {title: Github, icon: github, url: "https://github.com/mfathiabdallah"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/


plugins:
 - jekyll-feed
 - jemoji
 - jekyll-archives
 - jekyll-diagrams
 - jekyll-email-protect
 - jekyll-github-metadata
 - jekyll-imagemagick
 - jekyll-paginate-v2
 - jekyll/scholar
 - jekyll-sitemap
 - jekyll-target-blank
 - jekyll-twitter-plugin
 - jekyll-gist
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-toc
 - jekyll-redirect-from
 - jekyll-remote-theme
 
