title: "Mohamed Fathi Abdallah"
author: "Mohamed Fathi Abdallah"
description: "Mohamed Fathi Abdallah ©2022"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true      # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: flase       # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "mohamedfathiabdallah.pdf", title: "CV"}
  - {title: "Academic Page", url: "https://www.ugent.be/bw/foodscience/en/research/faculty/mohamed-fathi-abdallah-abdelmohsen.htm"}
  - {title: "Publications", file: "/publications.md"}
  - {title: "Media", file: "/media.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mohamed.fathi@ugent.be"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/MoFathiAbdallah"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/mohamed-fathi-abdallah-66126a38/"}
  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Mohamed-Abdallah-13"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=05FfukgAAAAJ&hl=en"}
  - {title: Orcid, icon: orcid, url: "https://orcid.org/0000-0002-3903-6452"}
  - {title: Github, icon: github, url: "https://github.com/mfathiabdallah"}
  - {title: Ghent University, icon: landmark, url: "https://www.ugent.be/"}


plugins:
 - jekyll-feed
 - jemoji
